
spring:
  #  Configuracion BASE DE DATOS
  #  https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts
  datasource: 
    url: jdbc:mysql://localhost:3306/recetario
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  Configuracion Creacion de tablas (Hibernate)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #MYSQL
  #  Que thymeleaf no guarde datos en cache
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
server:
  port: 8080
